<section class="admin__page-section edit-howtorefund">
    <div class="howtorefund-block-title">
        <h2><?= /* @noEscape */ __('How to execute a Full Refund?') ?></h2>
    </div>
    <div class="howtorefund-block-item">
        <ol type="1">
            <li><?= /* @noEscape */ __('On administration panel go to menu : Sales > Orders') ?></li>
            <li><?= /* @noEscape */ __('Select the transaction that you want to refund') ?></li>
            <li><?= /* @noEscape */ __('Click invoice menu on the left side') ?></li>
            <li><?= /* @noEscape */ __('Click the invoice data on the right side') ?></li>
            <li><?= /* @noEscape */ __('Click on Credit memo') ?></li>
            <li><?= /* @noEscape */ __('Then click the refund button') ?></li>
        </ol>
    </div>
    <div class="howtorefund-separator"/>
    <div class="howtorefund-block-title">
        <h2><?= /* @noEscape */ __('How to execute a Partial Refund?') ?></h2>
    </div>
    <div class="howtorefund-block-item">
        <ol type="1">
            <li><?= /* @noEscape */ __('On administration panel go to menu : Sales > Orders') ?></li>
            <li><?= /* @noEscape */ __('Select the transaction that you want to refund') ?></li>
            <li><?= /* @noEscape */ __('Click invoice menu on the left side') ?></li>
            <li><?= /* @noEscape */ __('Click the invoice data on the right side') ?></li>
            <li><?= /* @noEscape */ __('Click on Credit memo') ?></li>
            <li><?= /* @noEscape */ __('Choose the product quantity that you want to refund at Qty to Refund column') ?></li>
            <li><?= /* @noEscape */ __('Click the Update Qty’s button') ?></li>
            <li><?= /* @noEscape */ __('Input Refund Shipping, Adjustment Refund, Adjustment Fee') ?></li>
            <li><?= /* @noEscape */ __('Then click the refund button') ?></li>
        </ol>
    </div>
</section>
